/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Componentes.ManejoArchivo;
import Funciones.Alerta;
import Funciones.Numerico;
import javax.swing.JTextField;

public class Parametros extends javax.swing.JFrame {
    
    private int valorDuracion;
    private int valorTiempoSimulacion;
    private int valorNumEtapas;
    private int valorCostoCliente;
    private int seleccion;
    /**
     * Creates new form Prueba
     */
    public Parametros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        manual = new javax.swing.JRadioButton();
        archivo = new javax.swing.JRadioButton();
        siguiente = new javax.swing.JButton();
        archivo.setSelected(true);
        valorLlegada = new javax.swing.JTextField();
        unidadTiempo = new javax.swing.JComboBox<>();
        tiempoSimulacion = new javax.swing.JTextField();
        porcentajeLlegada = new javax.swing.JTextField();
        agregarLlegada = new javax.swing.JButton();
        agregarLlegada.setVisible(false);
        porcentajeLlegada.setVisible(false);
        valorLlegada.setVisible(false);
        tablaLlegadasArchivo = new javax.swing.JTextArea();
        tablaLlegadasManual = new javax.swing.JTextArea();
        leerArchivo = new javax.swing.JButton();
        costoCliente = new javax.swing.JTextField();
        duracion = new javax.swing.JTextField();
        maxServidores = new javax.swing.JTextField();
        maxClientes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setVisible(true);
        unidadLabel = new javax.swing.JLabel();
        unidad = new javax.swing.JComboBox<>();
        unidadLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(232, 225, 225));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo.setText("Simulador de Colas");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 790, 42));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Di Mella, D. Bermudez, D");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 11));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Ingeniería Informatica");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 15));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Unidad de tiempo a utilizar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Duración de la simulación");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tiempo de la simulación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Costo de espera del cliente por unidad de tiempo ($)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Costo por servidor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tiempos entre llegadas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, 20));

        manual.setBackground(new java.awt.Color(232, 225, 225));
        buttonGroup1.add(manual);
        manual.setText("Manual");
        jPanel1.add(manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              leerArchivo.setVisible(false);
              jScrollPane1.setVisible(false);
              jLabel12.setVisible(true);
              jLabel13.setVisible(true);
              agregarLlegada.setVisible(true);
              porcentajeLlegada.setVisible(true);
              valorLlegada.setVisible(true);
              jScrollPane2.setVisible(true);
            }
        });

        archivo.setBackground(new java.awt.Color(232, 225, 225));
        buttonGroup1.add(archivo);
        archivo.setText("Archivo");
        jPanel1.add(archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));
        archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              jLabel12.setVisible(false);
              jLabel13.setVisible(false);
              jScrollPane2.setVisible(false);
              porcentajeLlegada.setVisible(false);
              valorLlegada.setVisible(false);
              agregarLlegada.setVisible(false);
              leerArchivo.setVisible(true);
              jScrollPane1.setVisible(true);
            }
        });

        leerArchivo.setText("Abrir archivo");
        leerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(leerArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, 20));

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 570, 90));
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 570, 90));

        jLabel12.setText("Valor:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));
        jPanel1.add(valorLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 38, -1));

        jLabel13.setText("Porcentaje:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));
        jPanel1.add(porcentajeLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 42, -1));

        agregarLlegada.setText("Agregar");
        jPanel1.add(agregarLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 90, 20));
        agregarLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLlegadaActionPerformed(evt);
            }
        });
      
        siguiente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        siguiente.setText("Simular");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 525, 120, 30));
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        tablaLlegadasArchivo.setColumns(20);
        tablaLlegadasArchivo.setRows(5);
        jScrollPane1.setViewportView(tablaLlegadasArchivo);

        tablaLlegadasManual.setColumns(20);
        tablaLlegadasManual.setRows(5);
        jScrollPane2.setViewportView(tablaLlegadasManual);

        unidadTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutos", "Horas", "Dias", "Semanas", "Meses", "Años" }));
        jPanel1.add(unidadTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));
        jPanel1.add(tiempoSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 42, -1));
        jPanel1.add(maxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 42, -1));
        jPanel1.add(maxServidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 42, -1));
        jPanel1.add(costoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 42, -1));
        jPanel1.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 42, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Cantidad maxima de clientes");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        jPanel1.add(maxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 42, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Cantidad maxima de servidores");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        jPanel1.add(maxServidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 42, -1));

        unidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segundos", "Minutos", "Horas", "Dias", "Semanas", "Meses", "Años" }));
        unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadActionPerformed(evt);
            }
        });
        jPanel1.add(unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, 400, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        if(!Numerico.isNumeric(this.duracion.getText())){
            Alerta.mensajeError("La duración de simulación debe ser un valor numerico");
            this.duracion.setText("");
            return;
        }else{
            if(Integer.parseInt(this.duracion.getText())<=0){
                Alerta.mensajeError("La duración de la simulación no es valida");
                this.duracion.setText("");
                return;
            }
        }
        if(!Numerico.isNumeric(this.tiempoSimulacion.getText())){
            Alerta.mensajeError("El tiempo de simulación debe ser un valor númerico");
            this.tiempoSimulacion.setText("");
            return;
        }else{
            if(Integer.parseInt(this.tiempoSimulacion.getText())<=0){
                Alerta.mensajeError("El tiempo a simular no es valido");
                this.tiempoSimulacion.setText("");
                return;
            }
        }
        if(!Numerico.isNumeric(this.costoCliente.getText())){
            Alerta.mensajeError("El costo de espera por cliente debe ser númerico");
            this.costoCliente.setText("");
            return;
        }else{
            if(Integer.parseInt(this.costoCliente.getText())<0){
                Alerta.mensajeError("El costo de espera del cliente no es valido");
                this.costoCliente.setText("");
                return;
            }
        }
        if(!archivo.isSelected() && !manual.isSelected()){
            Alerta.mensajeError("No se selecciono una opcion para los tiempos entre llegadas");
            return;
        }
        /*
        if(manual.isSelected() && !this.tablaLlegadasM.isCompleted()){
            Alerta.mensajeError("El parametro: TIEMPOS ENTRE LLEGADAS, no esta completo");
            return;
        }
        if(archivo.isSelected() && !this.tablaLlegadasA.isCompleted()){
            Alerta.mensajeError("El parametro: TIEMPOS ENTRE LLEGADAS, no esta completo");
            return;
        }
        */
        if(manual.isSelected())
            this.seleccion = 0;
        else
            this.seleccion = 1;
        this.valorDuracion = Integer.parseInt(this.duracion.getText());
        this.valorTiempoSimulacion = Integer.parseInt(this.tiempoSimulacion.getText());
        this.valorCostoCliente = Integer.parseInt(this.costoCliente.getText());
        
        //this.setVisible(false);
        //ParametrosEtapas P = new ParametrosEtapas(this.valorNumEtapas,this);
        //P.setVisible(true);
    }//GEN-LAST:event_siguienteActionPerformed

    public int getValorDuracion() {
        return valorDuracion;
    }

    public int getValorTiempoSimulacion() {
        return valorTiempoSimulacion;
    }

    public int getValorNumEtapas() {
        return valorNumEtapas;
    }

    public int getValorCostoCliente() {
        return valorCostoCliente;
    }

    public String getUnidad() {
        return (String)unidad.getSelectedItem();
    }

    public String getUnidadTiempo() {
        return (String)unidadTiempo.getSelectedItem();
    }

    private void agregarLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLlegadaActionPerformed
        // TODO add your handling code here:
        if(!Numerico.isNumeric(this.valorLlegada.getText())){
            Alerta.mensajeError("El parametro: VALOR LLEGADA, no es numerico");
            this.valorLlegada.setText("");
            return;
        }else{
            if(Integer.parseInt(this.valorLlegada.getText())<=0){
                Alerta.mensajeError("El parametro: VALOR LLEGADA, no es valido");
                this.valorLlegada.setText("");
                return;
            }
        }
        if(!Numerico.isNumeric(this.porcentajeLlegada.getText())){
            Alerta.mensajeError("El parametro: PORCENTAJE LLEGADA, no es numerico");
            this.valorLlegada.setText("");
            return;
        }else{
            if(Integer.parseInt(this.porcentajeLlegada.getText())<=0){
                Alerta.mensajeError("El parametro: PORCENTAJE LLEGADA, no es valido");
                this.valorLlegada.setText("");
                return;
            }
        }
        //this.tablaLlegadasM.addtiempoEntreLlegadas(Integer.parseInt(this.valorLlegada.getText()),Integer.parseInt(this.porcentajeLlegada.getText()));
        //this.tablaLlegadasManual.setText(this.tablaLlegadasM.toString());
    }//GEN-LAST:event_agregarLlegadaActionPerformed

    private void unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadActionPerformed
        // TODO add your handling code here:
        this.unidadLabel.setText((String) this.unidad.getSelectedItem());
        this.unidadTiempo.removeAllItems();
        for(int i=this.unidad.getSelectedIndex();i<this.unidad.getItemCount();i++)
            if(!(i == this.unidad.getSelectedIndex()))
                this.unidadTiempo.addItem(this.unidad.getItemAt(i));
    }//GEN-LAST:event_unidadActionPerformed

    private void leerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerArchivoActionPerformed
        ManejoArchivo M = new ManejoArchivo();
        M.leerArchivoLlegadas();
        //this.tablaLlegadasA = M.getTablaLlegadas();
        //this.tablaLlegadasArchivo.setText(tablaLlegadasA.toString());
    }//GEN-LAST:event_leerArchivoActionPerformed
    
    
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton agregarLlegada;
    private javax.swing.JRadioButton archivo;
    private javax.swing.JTextField costoCliente;
    private javax.swing.JTextField duracion;
    private javax.swing.JTextField maxServidores;
    private javax.swing.JTextField maxClientes;
    private javax.swing.JButton leerArchivo; 
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton manual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tiempoSimulacion;
    private javax.swing.JTextField porcentajeLlegada;
    private javax.swing.JTextArea tablaLlegadasArchivo;
    private javax.swing.JTextArea tablaLlegadasManual;
    private javax.swing.JTextField valorLlegada;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel titulo;
    private javax.swing.JComboBox<String> unidad;
    private javax.swing.JLabel unidadLabel;
    private javax.swing.JLabel unidadLabel2;
    private javax.swing.JComboBox<String> unidadTiempo;
    // End of variables declaration//GEN-END:variables
}
