/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JTextField;

/**
 *
 * @author Mauricio
 */
public class Parametros extends javax.swing.JFrame {
    
    private int valorDuracion;
    private int valorTiempoSimulacion;
    private int valorNumEtapas;
    private int valorCostoCliente;
    private int seleccion;
    /**
     * Creates new form Prueba
     */
    public Parametros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        unidadTiempo = new javax.swing.JComboBox<>();
        tiempoSimulacion = new javax.swing.JTextField();
        leerArchivo = new javax.swing.JButton();
        costoCliente = new javax.swing.JTextField();
        duracion = new javax.swing.JTextField();
        maxServidores = new javax.swing.JTextField();
        maxClientes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();
        unidadLabel = new javax.swing.JLabel();
        unidad = new javax.swing.JComboBox<>();
        unidadLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(232, 225, 225));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo.setText("Simulador de Colas");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 790, 42));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Di Mella, D. Bermudez, D");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 11));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Ingeniería Informatica");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 15));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Unidad de tiempo a utilizar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Duración de la simulación");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tiempo de la simulación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Costo de espera del cliente por unidad de tiempo ($)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        unidadTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutos", "Horas", "Dias", "Semanas", "Meses", "Años" }));
        jPanel1.add(unidadTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));
        jPanel1.add(tiempoSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 42, -1));
        jPanel1.add(maxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 42, -1));
        jPanel1.add(maxServidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 42, -1));
        jPanel1.add(costoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 42, -1));
        jPanel1.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 42, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Cantidad maxima de clientes");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        jPanel1.add(maxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 42, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Cantidad maxima de servidores");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        jPanel1.add(maxServidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 42, -1));

        unidadLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        unidadLabel.setText("Segundos");
        jPanel1.add(unidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));
  
        leerArchivo.setText("Abrir archivo");
        leerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(leerArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, 20));

        unidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segundos", "Minutos", "Horas", "Dias", "Semanas", "Meses", "Años" }));
        jPanel1.add(unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, 400, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getValorDuracion() {
        return valorDuracion;
    }

    public int getValorTiempoSimulacion() {
        return valorTiempoSimulacion;
    }

    public int getValorNumEtapas() {
        return valorNumEtapas;
    }

    public int getValorCostoCliente() {
        return valorCostoCliente;
    }

    public String getUnidad() {
        return (String)unidad.getSelectedItem();
    }

    public String getUnidadTiempo() {
        return (String)unidadTiempo.getSelectedItem();
    }

    private void leerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerArchivoEntradaActionPerformed
    }//GEN-LAST:event_leerArchivoActionPerformed
    
    
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField costoCliente;
    private javax.swing.JTextField duracion;
    private javax.swing.JTextField maxServidores;
    private javax.swing.JTextField maxClientes;
    private javax.swing.JButton leerArchivo; 
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tiempoSimulacion;
    private javax.swing.JLabel titulo;
    private javax.swing.JComboBox<String> unidad;
    private javax.swing.JLabel unidadLabel;
    private javax.swing.JLabel unidadLabel2;
    private javax.swing.JComboBox<String> unidadTiempo;
    // End of variables declaration//GEN-END:variables
}
