/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Componentes.Funciones;
import Componentes.ManejoArchivo;
import java.text.DecimalFormat;

public class Salida extends javax.swing.JFrame {

  ManejoArchivo archivoSalida;

  public Salida() {
    initComponents();
    this.archivoSalida = new ManejoArchivo();
  }

  public void addInfo(String info) {
    this.tabla.setText(this.tabla.getText() + info);
  }

  public void setLabelsText(Funciones est, String unidad) {
    DecimalFormat numberFormat = new DecimalFormat("0.00");
    this.labelClientesLlegaron.setText(
        "Cantidad de clientes que llegaron: " + est.cantidadLlegadas
      );
    this.labelClientesSinEspera.setText(
        "Cantidad de veces que clientes no esperaron: " + est.clientesNoEsperan
      );
    this.labelClientesSeVa.setText(
        "Cantidad de veces que un cliente se va sin ser atendido: " +
        est.clientesSeVan
      );
    this.labelClienteEspera.setText(
        "Probabilidad de un cliente de esperar : " +
        numberFormat.format(est.probabilidadDeEsperar) +
        "%"
      );
    this.labelPorcentajeUtilizacion.setText(
        "Porcentaje promedio de utilizacion de servidores : " +
        numberFormat.format(100 * est.porcentajeUtilizacionGeneral) +
        "%"
      );
    this.labelTiempoSistemaPromedio.setText(
        "Tiempo promedio de un cliente el sistema : " +
        numberFormat.format(est.tiempoEnSistema) +
        " " +
        unidad
      );
    this.labelCostoEspera.setText(
        "Costo total por espera de clientes : " +
        numberFormat.format(est.costoEspera) +
        "$"
      );
    this.labelCostoServidores.setText(
        "Costo total por uso de servidores : " +
        numberFormat.format(est.costoDeServidor) +
        "$"
      );
    this.labelCostoOperacion.setText(
        "Costo por uso de sistema : " +
        numberFormat.format(est.costoOperacion) +
        "$"
      );
  }

  public ManejoArchivo getArchivoSalida() {
    return archivoSalida;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */

  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jPanel1 = new javax.swing.JPanel();
    titulo = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabla = new javax.swing.JTextArea();
    labelClientesLlegaron = new javax.swing.JLabel();
    labelClientesSinEspera = new javax.swing.JLabel();
    labelClientesSeVa = new javax.swing.JLabel();
    labelClienteEspera = new javax.swing.JLabel();
    labelPorcentajeUtilizacion = new javax.swing.JLabel();
    labelTiempoSistemaPromedio = new javax.swing.JLabel();
    labelCostoEspera = new javax.swing.JLabel();
    labelCostoServidores = new javax.swing.JLabel();
    labelCostoOperacion = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(232, 225, 225));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
    titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titulo.setText("Resultados de simulación");
    jPanel1.add(
      titulo,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 790, 42)
    );

    jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    jLabel1.setText("Estadisticas");
    jPanel1.add(
      jLabel1,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, 11)
    );

    labelClientesLlegaron.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelClientesLlegaron.setText("Cantidad de clientes que llegaron: ");
    jPanel1.add(
      labelClientesLlegaron,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 11)
    );

    labelClientesSinEspera.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelClientesSinEspera.setText("Cantidad de clientes que no epseran: ");
    jPanel1.add(
      labelClientesSinEspera,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 11)
    );

    labelClientesSeVa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelClientesSeVa.setText("Cantidad de clientes que se van: ");
    jPanel1.add(
      labelClientesSeVa,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 11)
    );

    labelClienteEspera.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelClienteEspera.setText("Probabilidad de un cliente de esperar: ");
    jPanel1.add(
      labelClienteEspera,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 11)
    );

    labelPorcentajeUtilizacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelPorcentajeUtilizacion.setText(
      "Porcentaje de utilizacion del sistema: "
    );
    jPanel1.add(
      labelPorcentajeUtilizacion,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 11)
    );

    labelTiempoSistemaPromedio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelTiempoSistemaPromedio.setText(
      "Tiempo promedio que el cliente estuvo en el sistema: "
    );
    jPanel1.add(
      labelTiempoSistemaPromedio,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, 11)
    );

    labelCostoEspera.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelCostoEspera.setText("Costo por espera de clientes: ");
    jPanel1.add(
      labelCostoEspera,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, 11)
    );

    labelCostoServidores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelCostoServidores.setText("Costo por uso de servidores: ");
    jPanel1.add(
      labelCostoServidores,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, 11)
    );

    labelCostoOperacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    labelCostoOperacion.setText("Costo por uso del sistema: ");
    jPanel1.add(
      labelCostoOperacion,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, 11)
    );

    jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    jLabel1.setText("Eventos");
    jPanel1.add(
      jLabel1,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 470, -1, 14)
    );

    tabla.setColumns(20);
    tabla.setRows(5);
    jScrollPane1.setViewportView(tabla);

    jPanel1.add(
      jScrollPane1,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 700, 390)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel1,
          javax.swing.GroupLayout.Alignment.TRAILING,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.PREFERRED_SIZE
        )
    );

    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          870,
          Short.MAX_VALUE
        )
    );

    jPanel1.getAccessibleContext().setAccessibleName("");

    pack();
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel labelClientesLlegaron;
  private javax.swing.JLabel labelClientesSinEspera;
  private javax.swing.JLabel labelClientesSeVa;
  private javax.swing.JLabel labelClienteEspera;
  private javax.swing.JLabel labelPorcentajeUtilizacion;
  private javax.swing.JLabel labelTiempoSistemaPromedio;
  private javax.swing.JLabel labelCostoEspera;
  private javax.swing.JLabel labelCostoServidores;
  private javax.swing.JLabel labelCostoOperacion;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea tabla;
  private javax.swing.JLabel titulo;
  // End of variables declaration//GEN-END:variables
}
